_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "checkpoints/voc/split2/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
    UNFREEZE_FC2: True
    BATCH_SIZE_PER_IMAGE: 256
    IOU_THRESHOLDS: [0.4]

  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.1
      DECAY:
        ENABLED: True
        STEPS: [2000]
        RATE: 0.5
      IOU_THRESHOLD: 0.5

INPUT:
  CROP:
    ENABLED: True
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800

DATASETS:
  TRAIN: ('voc_2007_trainval_all2_2shot',)
  TEST: ('voc_2007_test_all2',)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (3000,)
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 20

TEST:
  EVAL_PERIOD: 500

OUTPUT_DIR: "checkpoints/voc/ablation/split2/2shot_baseline"