_BASE_: "../../../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "checkpoints/voc/split1/R101_FPN_base1/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256
    IOU_THRESHOLDS: [0.4]

  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.2
      DECAY:
        ENABLED: True
        STEPS: [3000, 6000]
        RATE: 0.5
      IOU_THRESHOLD: 0.4 # equals the iou trehshold in roi head to use foreground only
      REWEIGHT_FUNC: 'exp'

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  CROP:
    ENABLED: True

DATASETS:
  TRAIN: ('voc_2007_trainval_all1_3shot',)
  TEST: ('voc_2007_test_all1',)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  GAMMA: 0.5
  STEPS: (4000,6000)
  MAX_ITER: 8000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 200

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 700

OUTPUT_DIR: "checkpoints/voc/ablation/3shot_CL_IoU_exp"