_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL: #/media/zeyu/8T/AI_MODEL/few_shot_learning/paper/boepaper2022/results/voc/split1_10shot_CL_IoU_boe_ok/model_final.pth /media/zeyu/8T/AI_MODEL/few_shot_learning/paper/boepaper2022/results/voc/split1_10shot_CL_IoU_boe_experiment2/model_0014999.pth
  WEIGHTS: "/sgzy_fsce_test2/media/zeyu/8T/AI_MODEL/few_shot_learning/paper/boepaper2022/results/voc/split1_10shot_CL_IoU_boe_experiment2/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256
    # SCORE_THRESH_TEST: 0.0

  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.5
      DECAY:
        ENABLED: True
        STEPS: [6000, 10000]
        RATE: 0.5
      IOU_THRESHOLD: 0.8  # high credibility proposals provide consistency

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  CROP:
    ENABLED: True

DATASETS:
  TRAIN: ('voc_2007_trainval_all1_10shot',)
  TEST: ('voc_2007_test_all1',)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  GAMMA: 0.5
  STEPS: (8000,13000)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 200

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 5000

OUTPUT_DIR: "checkpoints/voc/10shot_CL_IoU_seed_base_usc"